# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'music_des.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1010, 812)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("For_Qtdesiner/icon_main.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("QMenuBar::item:selected {\n"
"    background-color: rgba(16, 3, 113, 80);\n"
"}\n"
"\n"
"QMenuBar, QMenu {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(0, 0, 0, 255), stop:0.05 rgba(14, 8, 73, 255), stop:0.36 rgba(28, 17, 145, 255), stop:0.6 rgba(126, 14, 81, 255), stop:0.75 rgba(234, 11, 11, 255), stop:0.79 rgba(244, 70, 5, 255), stop:0.86 rgba(255, 136, 0, 255), stop:0.935 rgba(239, 236, 55, 255));\n"
"    color: rgb(255, 224, 249);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setStyleSheet("#widget {\n"
"    background-color: qconicalgradient(cx:0.5, cy:0.5, angle:0, stop:0 rgba(35, 40, 3, 255), stop:0.16 rgba(136, 106, 22, 255), stop:0.225 rgba(166, 140, 41, 255), stop:0.285 rgba(204, 181, 74, 255), stop:0.345 rgba(235, 219, 102, 255), stop:0.415 rgba(245, 236, 112, 255), stop:0.52 rgba(209, 190, 76, 255), stop:0.57 rgba(187, 156, 51, 255), stop:0.635 rgba(168, 142, 42, 255), stop:0.695 rgba(202, 174, 68, 255), stop:0.75 rgba(218, 202, 86, 255), stop:0.815 rgba(208, 187, 73, 255), stop:0.88 rgba(187, 156, 51, 255), stop:0.935 rgba(137, 108, 26, 255), stop:1 rgba(35, 40, 3, 255));\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    margin-right: 70px;\n"
"    margin-left: 70px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    border-radius: 3px;\n"
"    background-color: rgba(99, 149, 149, 0.5);\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"    border-radius: 3px;\n"
"    background-color: rgba(0, 0, 0, 50);\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Italic")
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("#label_2 {\n"
"    text-align: center;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.title_playlist = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Sitka Banner Semibold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.title_playlist.setFont(font)
        self.title_playlist.setObjectName("title_playlist")
        self.horizontalLayout_3.addWidget(self.title_playlist)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setStyleSheet("#label {\n"
"    background-color: rgb(138, 138, 68);\n"
"     border-top-left-radius: 50px;\n"
"     border-top-right-radius: 20px;\n"
"     border-bottom-left-radius: 20px;\n"
"}")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("For_Qtdesiner/music.svg"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.listMusics = QtWidgets.QListWidget(self.widget)
        self.listMusics.setMinimumSize(QtCore.QSize(300, 0))
        self.listMusics.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 255), stop:0.55 rgba(235, 148, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));\n"
"border: 3px solid rgb(255, 0, 4);\n"
"border-radius: 10px;")
        self.listMusics.setObjectName("listMusics")
        item = QtWidgets.QListWidgetItem()
        self.listMusics.addItem(item)
        self.horizontalLayout.addWidget(self.listMusics)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.musics_slider = QtWidgets.QSlider(self.widget)
        self.musics_slider.setStyleSheet("* {\n"
"  background: none !important;\n"
"}\n"
"\n"
"/* Оставляем фон для ползунка и линии */\n"
"input[type=\"range\"]::-webkit-slider-runnable-track,\n"
"input[type=\"range\"]::-moz-range-track,\n"
"input[type=\"range\"]::-ms-track {\n"
"  background: linear-gradient(to right, #ddd, #ddd) !important;\n"
"}\n"
"\n"
"QSlider {\n"
"  background-color: none;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"  background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"  height: 8px;\n"
"  margin: 2px 0;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"  background: #ffffff;\n"
"  border: 1px solid #5c5c5c;\n"
"  width: 10px;\n"
"  height: 14px;\n"
"  margin: -4px 0;\n"
"  border-radius: 2px;\n"
"}\n"
"")
        self.musics_slider.setOrientation(QtCore.Qt.Horizontal)
        self.musics_slider.setObjectName("musics_slider")
        self.horizontalLayout_2.addWidget(self.musics_slider)
        self.time = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.time.setFont(font)
        self.time.setObjectName("time")
        self.horizontalLayout_2.addWidget(self.time)
        self.horizontalLayout_2.setStretch(1, 20)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.last = QtWidgets.QPushButton(self.widget)
        self.last.setToolTipDuration(-1)
        self.last.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.last.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("For_Qtdesiner/icon_last.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.last.setIcon(icon1)
        self.last.setIconSize(QtCore.QSize(30, 30))
        self.last.setObjectName("last")
        self.horizontalLayout_4.addWidget(self.last)
        self.play_music = QtWidgets.QPushButton(self.widget)
        self.play_music.setStyleSheet("")
        self.play_music.setText("")
        self.play_music.setIconSize(QtCore.QSize(30, 30))
        self.play_music.setObjectName("play_music")
        self.horizontalLayout_4.addWidget(self.play_music)
        self.next = QtWidgets.QPushButton(self.widget)
        self.next.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("For_Qtdesiner/icon_next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.next.setIcon(icon2)
        self.next.setIconSize(QtCore.QSize(30, 30))
        self.next.setObjectName("next")
        self.horizontalLayout_4.addWidget(self.next)
        self.title_music = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.title_music.setFont(font)
        self.title_music.setStyleSheet("")
        self.title_music.setObjectName("title_music")
        self.horizontalLayout_4.addWidget(self.title_music)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)
        self.horizontalLayout_4.setStretch(2, 1)
        self.horizontalLayout_4.setStretch(3, 2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1010, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("For_Qtdesiner/icon_open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action.setIcon(icon3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.action.setFont(font)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.action_2.setFont(font)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.action_3.setFont(font)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("For_Qtdesiner/icon_description.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_4.setIcon(icon4)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.action_4.setFont(font)
        self.action_4.setObjectName("action_4")
        self.action_YouTube = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("For_Qtdesiner/icon_youtube.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_YouTube.setIcon(icon5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.action_YouTube.setFont(font)
        self.action_YouTube.setObjectName("action_YouTube")
        self.action_5 = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("For_Qtdesiner/icon_radio.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_5.setIcon(icon6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.action_5.setFont(font)
        self.action_5.setObjectName("action_5")
        self.action_6 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.action_6.setFont(font)
        self.action_6.setObjectName("action_6")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_YouTube)
        self.menu_2.addAction(self.action_2)
        self.menu_2.addAction(self.action_3)
        self.menu_3.addAction(self.action_4)
        self.menu_4.addAction(self.action_5)
        self.menu_4.addAction(self.action_6)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Музыкальный коллайдер"))
        self.label_2.setText(_translate("MainWindow", "Аудиопроигрыватель"))
        self.title_playlist.setText(_translate("MainWindow", "Альбом: ..."))
        __sortingEnabled = self.listMusics.isSortingEnabled()
        self.listMusics.setSortingEnabled(False)
        self.listMusics.setSortingEnabled(__sortingEnabled)
        self.time.setText(_translate("MainWindow", "00:00"))
        self.title_music.setText(_translate("MainWindow", "Название трека"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.menu_2.setTitle(_translate("MainWindow", "Альбом"))
        self.menu_3.setTitle(_translate("MainWindow", "Информация"))
        self.menu_4.setTitle(_translate("MainWindow", "Радио"))
        self.action.setText(_translate("MainWindow", "открыть"))
        self.action.setToolTip(_translate("MainWindow", "открыть Ctrl+X"))
        self.action.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.action_2.setText(_translate("MainWindow", "Создать"))
        self.action_3.setText(_translate("MainWindow", "Открыть"))
        self.action_4.setText(_translate("MainWindow", "Описания пользования"))
        self.action_YouTube.setText(_translate("MainWindow", "скачать с YouTube"))
        self.action_5.setText(_translate("MainWindow", "Открыть имеющиеся потоки"))
        self.action_6.setText(_translate("MainWindow", "Добавить поток"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
